In [2]:
import pandas as pd
import numpy as np

In [3]:
file = np.load("/Users/shashankkumar/Documents/GitHub/MacroEcon/data/step1/all_nta_agents.npy", allow_pickle=True)
file_dict = file.item()
# df = pd.DataFrame.from_dict(dict(file_dict), orient='index')
len(file_dict.keys())

3

In [4]:
file_dict

{'empty_ntas': ['QN0151',
  'BK0261',
  'MN0661',
  'QN0261',
  'QN0761',
  'BK0471',
  'BK0571',
  'BK0771',
  'BX1071',
  'BX1271',
  'QN0171',
  'QN0271',
  'QN0572',
  'QN0573',
  'QN0871',
  'QN1371',
  'QN8081',
  'QN8381',
  'BK0891',
  'BK1091',
  'BK1391',
  'BK1891',
  'BK1892',
  'BK1893',
  'BK5591',
  'BK5692',
  'BK5693',
  'BX0291',
  'BX0391',
  'BX0491',
  'BX0492',
  'BX0991',
  'BX1091',
  'BX2691',
  'MN0191',
  'MN1291',
  'MN1292',
  'MN6491',
  'QN0191',
  'QN0791',
  'QN0891',
  'QN1091',
  'QN1491',
  'QN8191',
  'QN8291',
  'QN8491',
  'SI0191',
  'SI0291',
  'SI9591',
  'SI9593'],
 'mapping': {'race': ['hispanic',
   'white',
   'black',
   'native',
   'other',
   'asian'],
  'education': ['high_school',
   'college_degree',
   'graduate_degree',
   'studying'],
  'employment_insurance': ['employed_insured',
   'employed_uninsured',
   'unemployed_insured',
   'unemployed_uninsured',
   'nolabor_insured',
   'nolabor_uninsured'],
  'age_gender': ['U19_M',
   'U19_F',
   '20t29_M',
   '20t29_F',
   '30t39_M',
   '30t39_F',
   '40t49_M',
   '40t49_F',
   '50t64_M',
   '50t64_F',
   '65A_M',
   '65A_F']},
 'valid_ntas': {'BK0101': {'nta_id': 'BK0101',
   'num_agents': 37518,
   'race': [5498, 27273, 937, 22, 2324, 1464],
   'education': [6718, 17468, 6566, 5339],
   'employment_insurance': [21557, 1853, 1446, 469, 3164, 271],
   'age_gender': [2445,
    2496,
    3327,
    3396,
    5728,
    5845,
    2833,
    2891,
    2300,
    2347,
    1736,
    2174]},
  'BK0102': {'nta_id': 'BK0102',
   'num_agents': 63316,
   'race': [18908, 34827, 1395, 11, 3270, 4905],
   'education': [12359, 24116, 10909, 11371],
   'employment_insurance': [35938, 2163, 1999, 375, 5754, 484],
   'age_gender': [5857,
    6321,
    6867,
    7410,
    8808,
    9505,
    3493,
    3771,
    3115,
    3363,
    2297,
    2509]},
  'BK0103': {'nta_id': 'BK0103',
   'num_agents': 47065,
   'race': [3957, 40619, 1571, 0, 681, 237],
   'education': [12876, 4507, 1173, 21580],
   'employment_insurance': [10463, 521, 707, 195, 5887, 205],
   'age_gender': [13202,
    12839,
    2549,
    2480,
    2218,
    2158,
    1741,
    1693,
    2165,
    2106,
    1835,
    2079]},
  'BK0104': {'nta_id': 'BK0104',
   'num_agents': 53478,
   'race': [20099, 20302, 6439, 58, 1715, 4865],
   'education': [15133, 18925, 5290, 10223],
   'employment_insurance': [26315, 2327, 1847, 233, 6870, 723],
   'age_gender': [5176,
    4288,
    6855,
    5677,
    6441,
    5335,
    3408,
    2823,
    4118,
    3412,
    2128,
    3817]},
  'BK0201': {'nta_id': 'BK0201',
   'num_agents': 24775,
   'race': [1722, 18465, 1337, 78, 1327, 1846],
   'education': [1137, 8570, 8930, 5070],
   'employment_insurance': [13085, 359, 570, 64, 2067, 104],
   'age_gender': [2703,
    2350,
    1733,
    1508,
    3016,
    2623,
    1732,
    1506,
    1959,
    1704,
    1670,
    2271]},
  'BK0202': {'nta_id': 'BK0202',
   'num_agents': 38546,
   'race': [6002, 18001, 5868, 65, 1846, 6764],
   'education': [5254, 13065, 10204, 8238],
   'employment_insurance': [20943, 778, 1262, 105, 4452, 163],
   'age_gender': [4002,
    3877,
    3669,
    3554,
    4758,
    4609,
    3238,
    3137,
    2293,
    2222,
    1313,
    1874]},
  'BK0203': {'nta_id': 'BK0203',
   'num_agents': 35051,
   'race': [5635, 11964, 10579, 193, 2909, 3771],
   'education': [6277, 12659, 6412, 7667],
   'employment_insurance': [16965, 934, 1472, 112, 4172, 195],
   'age_gender': [3658,
    3948,
    2917,
    3148,
    3664,
    3955,
    2302,
    2485,
    2405,
    2595,
    1490,
    2484]},
  'BK0204': {'nta_id': 'BK0204',
   'num_agents': 27368,
   'race': [3659, 12812, 7539, 14, 1395, 1949],
   'education': [2988, 11567, 6165, 5467],
   'employment_insurance': [15064, 529, 1230, 19, 2835, 114],
   'age_gender': [2362,
    2155,
    2560,
    2336,
    3793,
    3460,
    1920,
    1753,
    1892,
    1727,
    1125,
    2285]},
  'BK0301': {'nta_id': 'BK0301',
   'num_agents': 89224,
   'race': [17365, 33954, 31086, 79, 3454, 3286],
   'education': [21089, 27709, 9642, 24366],
   'employment_insurance': [40140, 3203, 2627, 640, 11590, 1212],
   'age_gender': [12036,
    12036,
    8975,
    8975,
    9658,
    9659,
    5113,
    5113,
    5636,
    5637,
    2356,
    4030]},
  'BK0302': {'nta_id': 'BK0302',
   'num_agents': 92298,
   'race': [15285, 14299, 55966, 102, 3814, 2832],
   'education': [26747, 28918, 10071, 20791],
   'employment_insurance': [39597, 3394, 3108, 724, 12985, 1540],
   'age_gender': [9764,
    10245,
    8313,
    8722,
    8118,
    8519,
    6098,
    6398,
    7184,
    7538,
    4331,
    7068]},
  'BK0401': {'nta_id': 'BK0401',
   'num_agents': 55156,
   'race': [29472, 16517, 3134, 128, 1849, 4056],
   'education': [16131, 19391, 4789, 11972],
   'employment_insurance': [26424, 5545, 1809, 346, 6934, 1010],
   'age_gender': [4782,
    4763,
    8310,
    8277,
    6210,
    6186,
    2907,
    2896,
    3461,
    3449,
    1581,
    2334]},
  'BK0402': {'nta_id': 'BK0402',
   'num_agents': 62987,
   'race': [31599, 10598, 15746, 77, 2348, 2619],
   'education': [20867, 19037, 3163, 15278],
   'employment_insurance': [27736, 3291, 1727, 403, 8960, 1269],
   'age_gender': [6622,
    6838,
    7370,
    7611,
    5669,
    5855,
    3579,
    3696,
    4437,
    4583,
    2616,
    4111]},
  'BK0501': {'nta_id': 'BK0501',
   'num_agents': 42755,
   'race': [29889, 1804, 7783, 53, 1343, 1883],
   'education': [17595, 8935, 1360, 10829],
   'employment_insurance': [16196, 1515, 654, 138, 6853, 933],
   'age_gender': [6161,
    6064,
    2930,
    2885,
    3342,
    3290,
    2765,
    2722,
    4003,
    3941,
    2032,
    2620]},
  'BK0502': {'nta_id': 'BK0502',
   'num_agents': 44841,
   'race': [15425, 981, 25051, 38, 1858, 1488],
   'education': [17923, 9141, 1058, 11977],
   'employment_insurance': [15177, 1314, 1783, 218, 7065, 667],
   'age_gender': [7331,
    6581,
    3274,
    2940,
    3684,
    3308,
    2823,
    2534,
    3751,
    3367,
    2298,
    2950]},
  'BK0503': {'nta_id': 'BK0503',
   'num_agents': 52314,
   'race': [12724, 961, 36401, 56, 1439, 733],
   'education': [19747, 13298, 1611, 13554],
   'employment_insurance': [17820, 801, 2620, 350, 8891, 1115],
   'age_gender': [6526,
    7156,
    3722,
    4081,
    3332,
    3655,
    3018,
    3311,
    4773,
    5234,
    3009,
    4497]},
  'BK0504': {'nta_id': 'BK0504',
   'num_agents': 15917,
   'race': [2479, 2460, 9950, 0, 590, 438],
   'education': [6223, 4195, 970, 3888],
   'employment_insurance': [5218, 218, 446, 15, 2431, 136],
   'age_gender': [2000,
    1510,
    980,
    740,
    994,
    750,
    991,
    748,
    1787,
    1349,
    1578,
    2490]},
  'BK0505': {'nta_id': 'BK0505',
   'num_agents': 48572,
   'race': [12605, 1341, 28313, 151, 1596, 4566],
   'education': [19982, 9050, 1002, 14454],
   'employment_insurance': [16465, 736, 1089, 126, 9181, 593],
   'age_gender': [7806,
    7382,
    3665,
    3466,
    3485,
    3296,
    2720,
    2572,
    4178,
    3952,
    2365,
    3685]},
  'BK0601': {'nta_id': 'BK0601',
   'num_agents': 63167,
   'race': [11423, 34594, 9340, 717, 3553, 3540],
   'education': [10087, 20587, 14669, 14053],
   'employment_insurance': [30509, 1320, 2091, 416, 6414, 604],
   'age_gender': [7237,
    8032,
    3345,
    3714,
    6492,
    7206,
    5182,
    5752,
    4548,
    5049,
    2941,
    3669]},
  'BK0602': {'nta_id': 'BK0602',
   'num_agents': 60202,
   'race': [7391, 41075, 3000, 53, 3405, 5278],
   'education': [3900, 20801, 20626, 11541],
   'employment_insurance': [32340, 839, 1665, 272, 4376, 375],
   'age_gender': [6239,
    7036,
    3297,
    3720,
    6490,
    7320,
    4468,
    5040,
    4480,
    5052,
    3268,
    3792]},
  'BK0701': {'nta_id': 'BK0701',
   'num_agents': 27023,
   'race': [3841, 18575, 689, 0, 1292, 2626],
   'education': [3461, 9278, 7102, 6608],
   'employment_insurance': [13222, 331, 661, 236, 2182, 238],
   'age_gender': [3406,
    3171,
    1181,
    1100,
    2473,
    2303,
    2454,
    2285,
    2595,
    2415,
    1714,
    1926]},
  'BK0702': {'nta_id': 'BK0702',
   'num_agents': 53050,
   'race': [30625, 12570, 2217, 38, 1534, 6066],
   'education': [18488, 13008, 5369, 13130],
   'employment_insurance': [20716, 4562, 1173, 369, 5492, 1036],
   'age_gender': [6619,
    6463,
    3948,
    3855,
    5784,
    5647,
    3708,
    3621,
    4165,
    4067,
    2250,
    2923]},
  'BK0703': {'nta_id': 'BK0703',
   'num_agents': 46012,
   'race': [14952, 4335, 979, 219, 544, 24983],
   'education': [21860, 7850, 1951, 11115],
   'employment_insurance': [16469, 4021, 1248, 401, 5143, 1181],
   'age_gender': [6222,
    6051,
    2837,
    2759,
    4175,
    4061,
    3224,
    3136,
    4095,
    3982,
    2346,
    3124]},
  'BK0801': {'nta_id': 'BK0801',
   'num_agents': 24082,
   'race': [2116, 13646, 4794, 4, 1764, 1758],
   'education': [2914, 9109, 7452, 3679],
   'employment_insurance': [13066, 699, 636, 85, 1869, 289],
   'age_gender': [1796,
    2421,
    1315,
    1772,
    2644,
    3564,
    1597,
    2153,
    1527,
    2059,
    1458,
    1776]},
  'BK0802': {'nta_id': 'BK0802',
   'num_agents': 87451,
   'race': [11937, 18542, 49596, 143, 4463, 2770],
   'education': [24716, 28999, 10881, 18554],
   'employment_insurance': [40885, 2577, 2918, 837, 12049, 1611],
   'age_gender': [8931,
    8147,
    9413,
    8586,
    8548,
    7798,
    5786,
    5279,
    7771,
    7089,
    3859,
    6244]},
  'BK0901': {'nta_id': 'BK0901',
   'num_agents': 51880,
   'race': [5435, 16149, 28711, 0, 1096, 489],
   'education': [13587, 17140, 4436, 13751],
   'employment_insurance': [21782, 1600, 1722, 395, 6111, 571],
   'age_gender': [7160,
    5604,
    5179,
    4053,
    4473,
    3502,
    3166,
    2479,
    4836,
    3786,
    2766,
    4876]},
  'BK0902': {'nta_id': 'BK0902',
   'num_agents': 48477,
   'race': [4087, 11982, 28690, 17, 2162, 1539],
   'education': [13230, 16995, 6020, 10278],
   'employment_insurance': [21575, 1529, 1311, 385, 5218, 894],
   'age_gender': [4458,
    4476,
    4042,
    4059,
    4367,
    4385,
    2866,
    2878,
    4303,
    4321,
    3162,
    5160]},
  'BK1001': {'nta_id': 'BK1001',
   'num_agents': 85796,
   'race': [16912, 50351, 2730, 97, 2571, 13135],
   'education': [19552, 30291, 13488, 18504],
   'employment_insurance': [36430, 3034, 1914, 383, 10214, 1097],
   'age_gender': [9939,
    8366,
    5788,
    4873,
    7113,
    5988,
    6085,
    5122,
    9379,
    7894,
    6313,
    8936]},
  'BK1002': {'nta_id': 'BK1002',
   'num_agents': 43548,
   'race': [5807, 17638, 628, 105, 475, 18895],
   'education': [17068, 10559, 3546, 10151],
   'employment_insurance': [16480, 1915, 1010, 282, 5576, 700],
   'age_gender': [5472,
    4588,
    2744,
    2301,
    3207,
    2690,
    2984,
    2503,
    4983,
    4178,
    3561,
    4337]},
  'BK1101': {'nta_id': 'BK1101',
   'num_agents': 102241,
   'race': [18472, 38963, 576, 566, 3001, 40663],
   'education': [38843, 25934, 7523, 23895],
   'employment_insurance': [38799, 6716, 2640, 747, 12942, 1248],
   'age_gender': [11999,
    12097,
    6450,
    6502,
    7619,
    7681,
    6423,
    6475,
    10507,
    10593,
    7041,
    8854]},
  'BK1102': {'nta_id': 'BK1102',
   'num_agents': 33765,
   'race': [5137, 14995, 765, 15, 1699, 11154],
   'education': [10408, 10106, 2969, 8444],
   'employment_insurance': [12518, 1815, 612, 135, 3971, 441],
   'age_gender': [4660,
    3922,
    1918,
    1616,
    2696,
    2270,
    2583,
    2175,
    3243,
    2731,
    2433,
    3518]},
  'BK1103': {'nta_id': 'BK1103',
   'num_agents': 60810,
   'race': [7835, 23937, 958, 46, 2140, 25894],
   'education': [21662, 16271, 4714, 14287],
   'employment_insurance': [22778, 2851, 1793, 475, 8365, 773],
   'age_gender': [7461,
    7169,
    3756,
    3610,
    4224,
    4059,
    4287,
    4119,
    6375,
    6125,
    4379,
    5246]},
  'BK1201': {'nta_id': 'BK1201',
   'num_agents': 30773,
   'race': [7509, 6230, 919, 0, 795, 15320],
   'education': [14038, 5129, 1373, 8305],
   'employment_insurance': [10542, 1703, 1088, 188, 3688, 623],
   'age_gender': [4662,
    4356,
    1677,
    1567,
    2736,
    2557,
    2257,
    2109,
    2408,
    2250,
    1857,
    2337]},
  'BK1202': {'nta_id': 'BK1202',
   'num_agents': 84493,
   'race': [6556, 69009, 531, 32, 2441, 5924],
   'education': [23812, 10971, 2622, 34959],
   'employment_insurance': [20272, 1959, 1766, 136, 10657, 714],
   'age_gender': [21130,
    20384,
    5764,
    5562,
    4307,
    4155,
    3452,
    3330,
    3978,
    3839,
    4021,
    4571]},
  'BK1203': {'nta_id': 'BK1203',
   'num_agents': 39486,
   'race': [6490, 18596, 3094, 35, 1759, 9512],
   'education': [9022, 11774, 6094, 10368],
   'employment_insurance': [16340, 1173, 986, 108, 4847, 356],
   'age_gender': [6601,
    4310,
    2749,
    1795,
    4126,
    2695,
    3538,
    2310,
    3790,
    2476,
    2048,
    3048]},
  'BK1204': {'nta_id': 'BK1204',
   'num_agents': 38337,
   'race': [3614, 29070, 502, 9, 970, 4172],
   'education': [10406, 8927, 3287, 12842],
   'employment_insurance': [11786, 1142, 654, 157, 5066, 562],
   'age_gender': [7321,
    6314,
    2494,
    2152,
    2237,
    1930,
    2368,
    2042,
    3020,
    2605,
    2564,
    3290]},
  'BK1301': {'nta_id': 'BK1301',
   'num_agents': 29353,
   'race': [4666, 14199, 3056, 26, 1067, 6339],
   'education': [9826, 8325, 2917, 6466],
   'employment_insurance': [9673, 1002, 1086, 181, 4358, 368],
   'age_gender': [3439,
    3200,
    1604,
    1494,
    1885,
    1755,
    1720,
    1601,
    3389,
    3155,
    2542,
    3569]},
  'BK1302': {'nta_id': 'BK1302',
   'num_agents': 51871,
   'race': [9809, 27178, 9140, 137, 1454, 4153],
   'education': [17489, 13873, 6503, 10759],
   'employment_insurance': [14481, 1405, 1280, 217, 8125, 790],
   'age_gender': [6237,
    5271,
    3057,
    2585,
    2648,
    2238,
    2771,
    2342,
    5482,
    4634,
    5594,
    9012]},
  'BK1303': {'nta_id': 'BK1303',
   'num_agents': 31295,
   'race': [3839, 22373, 263, 0, 2195, 2625],
   'education': [7795, 9797, 5939, 5478],
   'employment_insurance': [9531, 2356, 283, 105, 3529, 917],
   'age_gender': [3113,
    3041,
    1607,
    1569,
    1986,
    1939,
    1837,
    1795,
    3000,
    2930,
    3408,
    5070]},
  'BK1401': {'nta_id': 'BK1401',
   'num_agents': 69495,
   'race': [12351, 10975, 40560, 8, 2722, 2879],
   'education': [21025, 22596, 5849, 16771],
   'employment_insurance': [29936, 4745, 1445, 374, 8348, 1558],
   'age_gender': [7227,
    8150,
    5664,
    6388,
    5817,
    6561,
    4389,
    4951,
    5731,
    6463,
    2943,
    5211]},
  'BK1402': {'nta_id': 'BK1402',
   'num_agents': 42020,
   'race': [7525, 17059, 8097, 0, 1752, 7587],
   'education': [10733, 12538, 6177, 9985],
   'employment_insurance': [17720, 1452, 1222, 211, 4377, 762],
   'age_gender': [5361,
    4851,
    2943,
    2664,
    3419,
    3094,
    2744,
    2484,
    4179,
    3781,
    2697,
    3803]},
  'BK1403': {'nta_id': 'BK1403',
   'num_agents': 53963,
   'race': [4046, 37186, 3025, 36, 2202, 7468],
   'education': [11172, 15769, 7699, 15911],
   'employment_insurance': [17533, 2189, 910, 244, 6619, 907],
   'age_gender': [9193,
    7371,
    3488,
    2797,
    3874,
    3107,
    3170,
    2543,
    4913,
    3941,
    4706,
    4860]},
  'BK1501': {'nta_id': 'BK1501',
   'num_agents': 53438,
   'race': [6744, 35620, 1277, 84, 2301, 7412],
   'education': [14623, 14634, 5716, 14334],
   'employment_insurance': [19004, 1836, 1430, 229, 7316, 636],
   'age_gender': [7802,
    7617,
    3416,
    3336,
    3339,
    3261,
    3387,
    3307,
    4953,
    4837,
    3469,
    4714]},
  'BK1502': {'nta_id': 'BK1502',
   'num_agents': 42801,
   'race': [3174, 26058, 1321, 66, 1507, 10675],
   'education': [12282, 13000, 4863, 10170],
   'employment_insurance': [15710, 1295, 879, 197, 5522, 570],
   'age_gender': [5497,
    4954,
    2551,
    2299,
    2932,
    2644,
    2477,
    2234,
    4544,
    4095,
    3695,
    4879]},
  'BK1503': {'nta_id': 'BK1503',
   'num_agents': 68331,
   'race': [5903, 42914, 4302, 48, 2117, 13047],
   'education': [19814, 23003, 8040, 14126],
   'employment_insurance': [25871, 2219, 1253, 306, 8617, 800],
   'age_gender': [7572,
    6934,
    3902,
    3574,
    4407,
    4037,
    4425,
    4053,
    7425,
    6801,
    6779,
    8422]},
  'BK1601': {'nta_id': 'BK1601',
   'num_agents': 40043,
   'race': [8898, 3300, 26230, 112, 1023, 480],
   'education': [13828, 10577, 1869, 9795],
   'employment_insurance': [14758, 1489, 936, 54, 7013, 920],
   'age_gender': [5784,
    4928,
    3801,
    3239,
    3436,
    2927,
    2439,
    2079,
    3751,
    3197,
    1927,
    2535]},
  'BK1602': {'nta_id': 'BK1602',
   'num_agents': 49099,
   'race': [11334, 873, 34036, 93, 2049, 714],
   'education': [20754, 12817, 1216, 11941],
   'employment_insurance': [14514, 1491, 3333, 425, 10787, 1174],
   'age_gender': [5668,
    5996,
    3402,
    3600,
    3544,
    3749,
    3187,
    3371,
    4980,
    5268,
    2185,
    4149]},
  'BK1701': {'nta_id': 'BK1701',
   'num_agents': 45024,
   'race': [3082, 2942, 35687, 198, 2149, 966],
   'education': [15333, 13041, 3665, 11212],
   'employment_insurance': [19005, 2596, 1132, 201, 5824, 793],
   'age_gender': [5119,
    4959,
    3729,
    3612,
    4250,
    4117,
    2902,
    2811,
    3961,
    3838,
    2095,
    3631]},
  'BK1702': {'nta_id': 'BK1702',
   'num_agents': 35993,
   'race': [3138, 747, 28886, 47, 2272, 903],
   'education': [11279, 12728, 2333, 9162],
   'employment_insurance': [13539, 1332, 901, 280, 4752, 538],
   'age_gender': [3894,
    3727,
    2404,
    2301,
    2358,
    2257,
    2260,
    2163,
    3707,
    3548,
    3133,
    4241]},
  'BK1703': {'nta_id': 'BK1703',
   'num_agents': 40186,
   'race': [2548, 1283, 34330, 62, 1434, 529],
   'education': [13739, 13435, 2354, 9034],
   'employment_insurance': [17542, 1193, 964, 320, 3939, 846],
   'age_gender': [4635,
    4177,
    2622,
    2364,
    3106,
    2800,
    2693,
    2428,
    4444,
    4005,
    2661,
    4251]},
  'BK1704': {'nta_id': 'BK1704',
   'num_agents': 37761,
   'race': [2153, 1288, 31739, 0, 2393, 188],
   'education': [13891, 11856, 1498, 9100],
   'employment_insurance': [14145, 1331, 1721, 128, 4887, 1200],
   'age_gender': [3839,
    4366,
    2535,
    2882,
    1964,
    2233,
    2254,
    2564,
    4233,
    4812,
    2522,
    3557]},
  'BK1801': {'nta_id': 'BK1801',
   'num_agents': 71676,
   'race': [6259, 11131, 47066, 95, 3396, 3729],
   'education': [20543, 22660, 6359, 19472],
   'employment_insurance': [27939, 2133, 2021, 366, 8436, 772],
   'age_gender': [9573,
    8222,
    4663,
    4005,
    4897,
    4206,
    4604,
    3955,
    7977,
    6851,
    5318,
    7405]},
  'BK1802': {'nta_id': 'BK1802',
   'num_agents': 46698,
   'race': [3608, 29185, 6747, 129, 1707, 5322],
   'education': [12297, 14524, 5954, 11512],
   'employment_insurance': [18661, 889, 616, 45, 5199, 404],
   'age_gender': [5887,
    5983,
    2018,
    2052,
    2818,
    2864,
    2968,
    3017,
    4808,
    4886,
    4303,
    5094]},
  'BK1803': {'nta_id': 'BK1803',
   'num_agents': 90185,
   'race': [7881, 3903, 72612, 117, 3508, 2164],
   'education': [27127, 28486, 6071, 23702],
   'employment_insurance': [35167, 3196, 1987, 322, 12242, 1510],
   'age_gender': [11576,
    11439,
    6182,
    6110,
    5804,
    5735,
    5872,
    5803,
    9074,
    8967,
    5122,
    8501]},
  'BX0101': {'nta_id': 'BX0101',
   'num_agents': 54828,
   'race': [38153, 1620, 14278, 44, 587, 146],
   'education': [22205, 10701, 923, 16797],
   'employment_insurance': [14777, 2950, 1983, 244, 11274, 1320],
   'age_gender': [8778,
    8536,
    4221,
    4106,
    4382,
    4261,
    3191,
    3104,
    4463,

In [5]:
file_dict['mapping']

{'race': ['hispanic', 'white', 'black', 'native', 'other', 'asian'],
 'education': ['high_school', 'college_degree', 'graduate_degree', 'studying'],
 'employment_insurance': ['employed_insured',
  'employed_uninsured',
  'unemployed_insured',
  'unemployed_uninsured',
  'nolabor_insured',
  'nolabor_uninsured'],
 'age_gender': ['U19_M',
  'U19_F',
  '20t29_M',
  '20t29_F',
  '30t39_M',
  '30t39_F',
  '40t49_M',
  '40t49_F',
  '50t64_M',
  '50t64_F',
  '65A_M',
  '65A_F']}

In [18]:
import torch

# Create a 3x3 tensor with random 0s and 1s
tensor_e = torch.randint(5, (1, 10))
tensor_g = torch.randint(2, (1, 10))

print(tensor_e, tensor_g)

tensor([[0, 4, 4, 3, 4, 0, 1, 0, 1, 0]]) tensor([[0, 1, 0, 0, 0, 1, 1, 0, 0, 0]])

In [19]:
tensor_chunk = torch.chunk(tensor_g, 2, 1)
tensor_chunk

(tensor([[0, 1, 0, 0, 0]]), tensor([[1, 1, 0, 0, 0]]))

In [20]:
tensor_3 = torch.where(tensor_e == 3, 0, 1)
tensor_3

tensor([[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]])

In [24]:
t_eg = torch.logical_and(tensor_e == 4, tensor_g == 1).float()
t_eg

tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])